// <auto-generated />
using Conductus.EntityFramework.ConsoleApp;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Conductus.EntityFramework.ConsoleApp.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20201119131026_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Conductus.EntityFramework.ConsoleApp.HelloWorld", b =>
                {
                    b.Property<int>("HelloWorldId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .HasColumnType("TEXT");

                    b.HasKey("HelloWorldId");

                    b.ToTable("HelloWorlds");
                });
#pragma warning restore 612, 618
        }
    }
}
