// <auto-generated />
using HELLOWWORLD_EFCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HELLOWWORLD_EFCore.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20201118231158_ChangeToHelloWorld")]
    partial class ChangeToHelloWorld
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("HELLOWWORLD_EFCore.HelloWorld", b =>
                {
                    b.Property<int>("HelloWorldId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .HasColumnType("TEXT");

                    b.HasKey("HelloWorldId");

                    b.ToTable("HelloWorlds");
                });
#pragma warning restore 612, 618
        }
    }
}
